swagger: "2.0"
info:
  description: "Our API"
  version: "1.0.0"
  title: "User"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
host: "localhost:5050"
basePath: "/"
schemes:
- "http"
paths:
  /users:
    get:
      summary: "Return User List"
      description: ""
      operationId: "getUsers"
      produces:
      - "application/json"
      responses:
        200:
          description: "List of users"
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
    post:
      summary: "Create user"
      description: ""
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "Created user object"
          schema:
            $ref: "#/definitions/User"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
    xml:
      name: "User"